// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP pdSpecEst_ARMA(SEXP PhiSEXP, SEXP ThetaSEXP, SEXP ZSEXP, SEXP lenSEXP);
SEXP pdSpecEst_E_coeff(SEXP HSEXP, SEXP ESEXP);
SEXP pdSpecEst_E_coeff_inv(SEXP coeffSEXP, SEXP ESEXP);
SEXP pdSpecEst_Expm(SEXP PSEXP, SEXP HSEXP);
SEXP pdSpecEst_iSqrt(SEXP MSEXP);
SEXP pdSpecEst_kMean(SEXP MSEXP, SEXP muSEXP);
SEXP pdSpecEst_Logm(SEXP PSEXP, SEXP QSEXP);
SEXP pdSpecEst_Mid(SEXP ASEXP, SEXP BSEXP);
SEXP pdSpecEst_NormF(SEXP MSEXP);
SEXP pdSpecEst_RiemmDist(SEXP ASEXP, SEXP BSEXP);
SEXP pdSpecEst_solveMid(SEXP BSEXP, SEXP CSEXP);
SEXP pdSpecEst_Sqrt(SEXP MSEXP);

R_CallMethodDef callMethods[]  = {
  {"pdSpecEst_ARMA", (DL_FUNC) &pdSpecEst_ARMA, 4},
  {"pdSpecEst_E_coeff", (DL_FUNC) &pdSpecEst_E_coeff, 2},
  {"pdSpecEst_E_coeff_inv", (DL_FUNC) &pdSpecEst_E_coeff_inv, 2},
  {"pdSpecEst_Expm", (DL_FUNC) &pdSpecEst_Expm, 2},
  {"pdSpecEst_iSqrt", (DL_FUNC) &pdSpecEst_iSqrt, 1},
  {"pdSpecEst_kMean", (DL_FUNC) &pdSpecEst_kMean, 2},
  {"pdSpecEst_Logm", (DL_FUNC) &pdSpecEst_Logm, 2},
  {"pdSpecEst_Mid", (DL_FUNC) &pdSpecEst_Mid, 2},
  {"pdSpecEst_NormF", (DL_FUNC) &pdSpecEst_NormF, 1},
  {"pdSpecEst_RiemmDist", (DL_FUNC) &pdSpecEst_RiemmDist, 2},
  {"pdSpecEst_solveMid", (DL_FUNC) &pdSpecEst_solveMid, 2},
  {"pdSpecEst_Sqrt", (DL_FUNC) &pdSpecEst_Sqrt, 1},
  {NULL, NULL, 0}
};

void R_init_pdSpecEst(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

